PM: suspend: mark `sys_sync_queue` as maybe unused
fixes the following:

../kernel/power/suspend.c:774:12: error: unused function 'sys_sync_queue' [-Werror,-Wunused-function]
static int sys_sync_queue(void)
           ^
1 error generated.

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>