techpack/audio: wcd-mbhc-v2: Nuke unused variables
Fixes:
../techpack/audio/asoc/codecs/wcd-mbhc-v2.c:585:5: error: unused variable 'fsm_en' [-Werror,-Wunused-variable]
        u8 fsm_en = 0;
           ^
../techpack/audio/asoc/codecs/wcd-mbhc-v2.c:584:7: error: unused variable 'is_pa_on' [-Werror,-Wunused-variable]
        bool is_pa_on = false;
             ^
2 errors generated.

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>