gpu/drm: dsi-staging: Guard `dsi_panel_1p8_on_off() & mdss_tp_black_gesture_status()`
*Previous commits on nuking runtime conditions for get_project() & is_project() guarded the use of these functions under Realme 5 pro macro.
 as we compile our kernel for Realme XT, The compilation errors out as these were unused.

Thus guard these functions under Realme 5 Pro macro as well to avoid errors.

Fixes the following:

../drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:121:12: error: unused function 'mdss_tp_black_gesture_status' [-Werror,-Wunused-function]
static int mdss_tp_black_gesture_status(void){
           ^
../drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:689:12: error: unused function 'dsi_panel_1p8_on_off' [-Werror,-Wunused-function]
static int dsi_panel_1p8_on_off(struct dsi_panel *panel , int value)
           ^
2 errors generated.
make[5]: *** [../scripts/Makefile.build:334: drivers/gpu/drm/msm/dsi-staging/dsi_panel.o] Error 1
make[4]: *** [../scripts/Makefile.build:646: drivers/gpu/drm/msm] Error 2
make[3]: *** [../scripts/Makefile.build:646: drivers/gpu/drm] Error 2
make[2]: *** [../scripts/Makefile.build:646: drivers/gpu] Error 2
make[2]: *** Waiting for unfinished jobs....

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>