drm: msm: nuke unsued label `fail`
the label "fail" is unused after commit https://github.com/dakkshesh07/parallax_kernel_realme_rmx1921/commit/96393660e25c03a3201d926865d431267110ab68

upstream does not have the CAF commit https://github.com/dakkshesh07/parallax_kernel_realme_rmx1921/commit/7e5bda56d2da2712c24159bd7ad3546ee0d61e81
which removed the the use of fail label for which upstream had left this label and didn't remove.

we wont need this, so remove it.

fixes the following:

../drivers/gpu/drm/msm/msm_gem.c:1080:1: error: unused label 'fail' [-Werror,-Wunused-label]
fail:
^~~~~
1 error generated.
make[5]: *** [../scripts/Makefile.build:334: drivers/gpu/drm/msm/msm_gem.o] Error 1
make[4]: *** [../scripts/Makefile.build:646: drivers/gpu/drm/msm] Error 2
make[3]: *** [../scripts/Makefile.build:646: drivers/gpu/drm] Error 2
make[2]: *** [../scripts/Makefile.build:646: drivers/gpu] Error 2
make[2]: *** Waiting for unfinished jobs....

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>