arm64/configs: RMX1921: disable DRM_DP_CEC
breaks build, not useful for us as we dont want HDMI CEC support.

fixes:
../drivers/gpu/drm/drm_dp_cec.c:202:2: error: implicit declaration of function 'cec_received_msg' [-Werror,-Wimplicit-function-declaration]
        cec_received_msg(adap, &msg);
        ^
../drivers/gpu/drm/drm_dp_cec.c:218:3: error: implicit declaration of function 'cec_transmit_attempt_done' [-Werror,-Wimplicit-function-declaration]
                cec_transmit_attempt_done(adap, CEC_TX_STATUS_OK);
                ^
../drivers/gpu/drm/drm_dp_cec.c:336:18: error: implicit declaration of function 'cec_allocate_adapter' [-Werror,-Wimplicit-function-declaration]
        aux->cec.adap = cec_allocate_adapter(&drm_dp_cec_adap_ops,
                        ^
../drivers/gpu/drm/drm_dp_cec.c:336:18: note: did you mean 'cec_delete_adapter'?
../include/media/cec.h:248:20: note: 'cec_delete_adapter' declared here
static inline void cec_delete_adapter(struct cec_adapter *adap)
                   ^
../drivers/gpu/drm/drm_dp_cec.c:336:16: error: incompatible integer to pointer conversion assigning to 'struct cec_adapter *' from 'int' [-Werror,-Wint-conversion]
        aux->cec.adap = cec_allocate_adapter(&drm_dp_cec_adap_ops,
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>